export const AUTH = 'AUTH';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USERS = 'FETCH_USERS';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const LOGOUT = 'LOGOUT';
export const END_LOADING_USERS = 'END_LOADING_USERS';
export const START_LOADING_USERS = 'START_LOADING_USERS';
export const FETCH_ONE_USER = 'FETCH_ONE_USER';
export const USERS_TO_FOLLOW = 'USERS_TO_FOLLOW';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const GET_FOLLOWERS = 'GET_FOLLOWERS';
export const GET_FOLLOWINGS = 'GET_FOLLOWINGS';

export const CREATE_POST= 'CREATE_POST';
export const FETCH_FOLLOWINGS_POSTS='FETCH_FOLLOWINGS_POSTS';
export const FETCH_NOT_FOLLOWINGS_POSTS='FETCH_NOT_FOLLOWINGS_POSTS';
export const LIKE_POST = 'LIKE_POST';
export const DISLIKE_POST = 'DISLIKE_POST';
export const COMMENT_POST = 'COMMENT_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const FETCH_DONATIONS_BY_SEARCH = 'FETCH_DONATIONS_BY_SEARCH';
export const FETCH_DONATION = 'FETCH_DONATION';
export const END_LOADING_POSTS = 'END_LOADING_POSTS';
export const START_LOADING_POSTS = 'START_LOADING_POSTS';
export const FETCH_LATEST_DONATIONS='FETCH_LATEST_DONATIONS';

export const FETCH_FOLLOWINGS_STORIES='FETCH_FOLLOWINGS_STORIES';
export const CREATE_STORY= 'CREATE_STORY';
export const LIKE_STORY = 'LIKE_STORY';
export const DISLIKE_STORY = 'DISLIKE_STORY';
export const COMMENT_STORY = 'COMMENT_STORY';
export const UPDATE_STORY = 'UPDATE_STORY';
export const END_LOADING_STORIES = 'END_LOADING_STORIES';
export const START_LOADING_STORIES = 'START_LOADING_STORIES';
export const FETCH_ALL_STORIES = 'FETCH_ALL_STORIES';
export const LATEST_STORY = 'LATEST_STORY';

export const CREATE_CATEGORY= 'CREATE_CATEGORY';
export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';
export const FETCH_CATEGORY_BY_SEARCH = 'FETCH_CATEGORY_BY_SEARCH';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const END_LOADING_CATEGORIES = 'END_LOADING_CATEGORIES';
export const START_LOADING_CATEGORIES = 'START_LOADING_CATEGORIES';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const FETCH_MESSAGES_FROM_CONVERSATION = 'FETCH_MESSAGES_FROM_CONVERSATION';
export const NEW_MESSAGE = 'NEW_MESSAGE';

export const SET_ACTIVE_CONVERSATION = 'SET_ACTIVE_CONVERSATION';
export const FETCH_ALL_CONVERSATIONS = 'FETCH_ALL_CONVERSATIONS';
export const CREATE_CONVERSATION = 'CREATE_CONVERSATION';

export const REGISTER_USER_IN_CHAT = 'REGISTER_USER_IN_CHAT';
export const FETCH_USERS_BY_ID = 'FETCH_USERS_BY_ID';
export const USERS_CONVERSATIONS = 'USERS_CONVERSATIONS';
export const ALL_MESSAGES_IN_CONVERSATION = 'ALL_MESSAGES_IN_CONVERSATION';
